# Generated by Django 2.1 on 2019-11-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unrealizedGains', models.FloatField()),
                ('expRet', models.FloatField()),
                ('beta', models.FloatField()),
            ],
        ),
    ]
