# Generated by Django 2.1 on 2019-11-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('buyRate', models.FloatField(default=0.0, null=True)),
                ('buyDate', models.DateField(blank=True, default='', null=True)),
                ('sellRate', models.FloatField(default=0.0, null=True)),
                ('sellDate', models.DateField(blank=True, default='', null=True)),
                ('unrealizedGains', models.FloatField(default=0.0, editable=False, null=True)),
                ('realizedGains', models.FloatField(default=0.0, editable=False, null=True)),
                ('target', models.FloatField(default=0.0, null=True)),
                ('beta', models.FloatField(default=0.0, editable=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='realizedGains',
            field=models.FloatField(blank=True, default=0.0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='beta',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='expRet',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='unrealizedGains',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='portfolio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio'),
        ),
    ]
